services:
  - type: web
    name: studybuddy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FIREBASE_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false 